name: Generate doc
on:
  push:
    branches:
    - master
    - 2022-06
  pull_request:
    branches:
    - master

jobs:
  build-doc:
    runs-on: ubuntu-20.04
    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run docker
        uses: addnab/docker-run-action@v3
        with:
            image: reitzig/texlive-full:latest
            # image: ghcr.io/xu-cheng/texlive-full:latest
            options: |
              --volume ${{ github.workspace }}/:/workspace
            shell: bash
            run: |
              uname -a
              cat /etc/*release

              id
              pwd
              ls -lh

              cd /workspace
              which latexmk

              apk add --no-cache python3 py3-pip make gcc zlib-dev libffi-dev openssl-dev musl-dev ghostscript
              python3 --version


              python3 -m venv abc
              source ./abc/bin/activate
              python3 -m ensurepip

              python3 -m pip install -r ./docs/requirements.txt

              cd docs
              make html
              touch build/html/.nojekyll

              make latex && \
              mkdir -pv build/html/_static && \
              cd build/latex && \
              latexmk -pdf -dvi -ps- notes.tex && \
              cp -v notes.pdf ../html/_static/

      - name: Show files
        shell: bash
        run: |
          ls -lh docs/build
          ls -lh docs/build/html
          ls -lh docs/build/latex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: notes.pdf
          path: docs/build/latex/notes.pdf

      - name: Deploy
        # if: github.event_name == 'push' && github.ref == 'ref/head/master'
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
