name: Generate doc
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r ./docs/requirements.txt

      - name: Build doc
        shell: bash
        run: |
          cd docs
          python3 -m pip install -r ./requirements.txt
          make html
          touch build/html/.nojekyll

          make latex

      - name: Build pdf
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd docs/build/latex
            latexmk -pdf -dvi -ps- notes.tex
            cp -v notes.pdf ../html/_static/

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
